### ISSUE TITLE
ToolProperties.getHeadMaterial NPE

### ISSUE THREAD

**Issue by Katalliaan** [Katalliaan/Rubedo#77] opened 2015-11-03 05:58 UTC
Woggy shared the [following report](http://pastebin.com/x91ABApU), and examining the relevant entries in the inventory, I'm struggling to see why

![NBTExplorer examining inventory](https://i.imgur.com/aNJhmUx.png)

Those were the only Rubedo tools in the inventory (the other 5-entry tag was a wand), and all the heads appear to be valid when examined.

**Comment by Katalliaan** [comment] 2015-11-03 06:13
Extra info, after the tags for the Rubedo tools were removed:

<woggy> *deletes, reopens*
<woggy> what. the. mango.
<Katalliaan> ?
<Katalliaan> those three tools are the only ones you have, right?
<woggy> confirm rubedo tools are gone from inv. still crashes with exact same error.
<woggy> only ones in inv. there's a couple of shitty broken ones in a chest somewhere.
<Katalliaan> but not out in the world
<woggy> nope.

**Comment by SimonMeskens** [comment] 2015-11-03 07:06
We could add an "error" material, so that can never NPE, it will always return something. We should make it visually bright, so bugged out tools can be identified.

**Comment by woggy** [comment] 2015-11-03 15:31
Deleted the entire set of inventory tags just to see, and it booted up fine (though, of course, with no stuff). Makes it seem like it's looking for tool data on something that's not a Rubedo tool at all. Given that my inventory was almost entirely full when this happened, it's going to be kinda tedious to pinpoint which item's causing the problem, but I'll report back when I find it.

**Comment by woggy** [comment] 2015-11-03 17:03
Had a mysterious Rubedo axe from somewhere, missing Tag data. Have since deleted it.

**Comment by woggy** [comment] 2015-11-04 12:50
Had another crash, same error. Deleted the offending item again.  Here's the weird part. The item was listed in NBT as having item id 4626, which in my Creative world is listed as Oceancraft Raw Perch. However, when I load up my Survival world, item 4626 is listed as being the Rubedo Sword (raw perch is item id 4582). Am I missing something about how item IDs are generated that makes it not consistent from world to world?

Immediately before the crash I was in shallow water, but about, mmm, 30s before the crash I'd killed a Thaumcraft-champion-mob Iron Zombie, who was wielding a sword. I'm guessing that that may have been where the bad item came from, but not sure how to attempt to reproduce it (or if it is the case, why it'd have waited half a minute before crashing).

**Comment by Katalliaan** [comment] 2015-11-04 13:47
> Am I missing something about how item IDs are generated that makes it not consistent from world to world?

Forge stores IDs on a world-to-world basis. If some item or block has been added/removed since you started your world, the IDs on a freshly generated world will likely be different.

**Comment by SimonMeskens** [comment] 2015-11-04 14:27
Yeah, always check ids in the world they originated from, they change from world to world indeed.

So, there seems to be a chance that it's due to mob held stuff being corrupt. I'll have a look. Are you able to show us the NBT for the offending items in any way?

**Comment by woggy** [comment] 2015-11-04 14:36
At this point I've deleted it (so no screencap, sorry), but. The NBTExplorer listing for it only had four entries (Count, Damage, id, slot) and the tag entry was completely missing.

**Comment by SimonMeskens** [comment] 2015-11-04 15:07
For weird bugs like this: potentially a server/client bug. Not sure how I can reproduce this bug to allow for testing though.

**Comment by SimonMeskens** [comment] 2015-11-04 18:14
wontfix, not a Rubedo bug, but a Mini Bosses bug

**Closed** 2015-11-05 04:09 UTC
Labels: bug, wontfix
